name: Release unsigned IPA

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    name: Build IPA
    runs-on: macos-14

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Build Project for iOS
        run: |
          # Proje dosyasını ve otomatik olarak ilk Scheme adını bulur
          PROJ=$(ls -d *.xcodeproj | head -n 1)
          SCHEME=$(xcodebuild -list -project "$PROJ" | awk '/Schemes:/{flag=1; next} /^[[:space:]]*$/{flag=0} flag' | xargs | awk '{print $1}')
          
          echo "Building project: $PROJ with scheme: $SCHEME"

          xcodebuild build \
            -project "$PROJ" \
            -scheme "$SCHEME" \
            -sdk iphoneos \
            -configuration Release \
            -derivedDataPath build \
            CODE_SIGNING_ALLOWED=NO \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGN_IDENTITY="" \
            AD_HOC_CODE_SIGNING_ALLOWED=YES

      - name: Create IPA Package
        run: |
          mkdir -p Payload
          cp -r build/Build/Products/Release-iphoneos/*.app Payload/
          zip -r GestaltEdit.ipa Payload

      - name: Upload IPA Artifact
        uses: actions/upload-artifact@v4
        with:
          name: GestaltEdit-IPA
          path: GestaltEdit.ipa
